### PR TITLE
Olwa/dev

### PR DESCRIPTION
**Pull request by owalk**

### CODE REVIEW

**Comment by owalk** [comment]
This is just the first round of collision detection changes. Future updates will needs these changes, so let's push them out as a WIP

**Review by Conor-McNierney — APPROVED** [review]

**Review by Sean-Nishi — APPROVED** [review]
Looks good but without in wall.py's hitbox having some offset there is no 3d effect/sprite overlap to give illusion of 3d. Might want to undo that in the future.

**Comment by owalk** [comment]
> Looks good but without in wall.py's hitbox having some offset there is no 3d effect/sprite overlap to give illusion of 3d. Might want to undo that in the future.

Walls that have a reduced hitbox need to be the 'top' wall or in other words not have any consecutive wall in the tile above them, otherwise, it leaves a gap for sprites to run through. The reduced hitbox on top walls can be added to the spec and implemented later with more thought into how it will work.

**Comment by owalk** [comment]
New tasks have been defined here
[Issue 87](https://github.com/Sean-Nishi/Lunk-Game/issues/87)
[Issue 88](https://github.com/Sean-Nishi/Lunk-Game/issues/88)

**Pull request merged**
