### PR TITLE
Olwa/dev

### PR DESCRIPTION
**Pull request by owalk**

### CODE REVIEW

**Comment by Sean-Nishi** [comment]
Let me know if you have some time today and we can go over your changes from last night. I might have to leave before 3 today though

**Comment by owalk** [comment]
I've been out of the house since I woke up, there might be some time before I sleep tonight if your free. The PR isn't ready for review yet tho

**Comment by owalk** [comment]
This is now ready for review. I've cut back, for now, to just black and flake8 to get us started. We can fix up the README for pulling in dependencies and using the tools next PR - documented here https://github.com/Sean-Nishi/Lunk-Game/issues/22

**Review by Sean-Nishi — APPROVED** [review]
Looks good. level1.py just needs to import the map from a csv file and it will look super clean!

**Pull request merged**
